export const links = [
  { name: "About", to: "/about" },
  { name: "Contact", to: "/contact" },
  { name: "Courses", to: "/courses" },
  { name: "IERY", to: "/iery" },
  { name: "Services for Community", to: "/plantation" },
  { name: "Reviews", to: "/reviews" },
  { name: "Lifeskills Training Program", to: "/lst" },
  { name: "Know More", to: "/know-more" },
  { name: "Research Guidance", to: "/research-guidance" },
  { name: "Website Developers", to: "/developers" },
  { name: "Photo Gallery", to: "/photo-gallery" },
  { name: "Video Gallery", to: "/video-gallery" },
  { name: "Documents", to: "/documents" },
];
